export const skills = [
  'HTML',
  'CSS/SCSS',
  'Javascript',
  'Typescript',
  'React',
  'Redux',
  'GraphQL',
  'Next.js',
  'Material-UI',
  'Wordpress',
  'Node.js',
  'RESTful APIs',
  'Responsive Design',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Adobe XD',
  'Figma',
  'Version Control(Git)',
  'Agile Development',
  'Team Collaboration'
]